dist: xenial
sudo: required

language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11

env:
  global:
    - MY_PV=1.0.2-SNAPSHOT

addons:
  sonarcloud:
    organization: jtidy-github
    token:
      secure: jpBEsJEcotUiJoLLVzoXwICY287wf/Tt4BGg6nQOIM10iF5XlUrdPFJoSwLAAnmkjXlcAczLcdqCqq9m4GtNB3TNW591ScO/H685E3mT4Iureea+1Nycw9S96EEoQRCeV0Lbo9cxc6iLWbOibtXfslJs3nZyIl1y+GiS3k0vAjzKbLEI/mvUSbJZYSDU+w6RtOFITW+td78O4Q/qtOOsjIoJDJUJ8jAiw8HpWkGQ/ko16by+JX57Wt8qNfQuy0f20xn7NnorK+mYStZ367g/QZa1z4ago/CwkuZ7MhS6yHwUNzYUPSK36KwLkU5oG2UYMnCQCA6xQo4vhXfOwpiV8PVFX33JDU0s3DbBc0cumyDAkrKDyCkZRcLLCk6nSv2E87eXugixJS9WwP8LB29dKiYBPrHI5eNlYoEjHhJoO37CsFtkVBwR80JxvvcPkYeDkvhfyj4omj4+ZWVX2UIB27PVoxOhsea0WdttxPSlzPhtLIBarJPAYQhWcTQxUkmUr+AGvMHzsFkmXFiHPBk6swY4eT8LlG7pbz1t59foAUDm19XHCnBfug9yjiEugw0sag7b6BcHPfo89zuiYR5t+s5xn2Noec7etcox0DBtbP/ojIFKowSy2T6m0PrYNw0+0Ud96qNjplesmLSjtQGCmPuOQbYwMmRhKCxYeVgaNYY=

jobs:
  include:
    - stage: Deploy
      if: tag =~ ^[0-9]+.*
      env:
        - secure: "PwojT+dbyGlOFUpOV2dqSBcbfGMs0AyZaxYrfkgbpNyEq2VEl7Ns3aQNn0ofn5MFStgXCtU0bS3J/ZUb1ufPIuREVmxD32OOMSB/jqr1J+/riyaHMVJmq0wIBpcm701gwgY1VYhWhv1tcHmPesziN704UuzvQwRNy9hnuHLz+aw/GzfjeubficOzReW4/TjNQA7bgsY+fiylW0E/fgIZWg5UcaeExZkhT+RvMDgiyk/g0Q4rW/YYlU+Ww53VwNaGIIRIzTAtMaLgZlmdTs80BBmVgdYeTwxVcpRole5Wmxxk1NZ+xdQLrumSm8z9FRiq85mYlByQBzdSfkNYbhI+o3SReDg3Vk1zccLwOwFheauLE+fJlXtY6sVZenSC0MhsrOAOxHtIyr4mcp3l6AuOQaHWQxhJ3FNoICn5XQauT6tM3fqqVcXLdy/KxiQpbxEGgE3O6H7S56YQEMLzjAnGtQuKZFRZPT7ULBIES5qIz05ZjmAkAXlG3nYfHHlxX6B7SiIoZ6GjmNWD3mNdcX7ZgJsRrQkrdpd7MjT0H7B0ydNqoM4J1AAfbp15NXvQu62uwzYgSxsQdq96DQ/PQYq3S9nG6m2xNFB98T8K8XEOITpXCznLC+SSeVPMSLEyFcrykM1cH5ificMcW0k07Qp0JmH5ZN+mCLpGWse2NKk7jus="
        - secure: "rmh6l+WGVnrIihHd6QSv5KA4PyPvYqa8OHJk8iQzSZXlfI+ZBHbXGG/MNmBXWUf+2s2T4MnNkcmbU+NAaI8EiIpeBxvTm5fhwFHEzqR7HCLFgODX1HvE0wJM2swvCEu+Lza8k61WaTl7jzcp55lZgUc7N5EUipW+eB81kbhr6fkBPt4IqUYoHtOhU2jdgMLUcssZf2KQnpTiNQ3zs+UQkCAmc+/bgQjEWmfr8foy8MMrLz1/8rvOrqdG73/8pfDYua7aykNgjmQcjUPR7fCx2JKnz3b9/yH+HbFqSNFC1i4ObtqK8+BRxB0rXdPP7cpydOUzkHQv+0587t3qHSkSS2eGxbvSF86qeev3rjsVhL3lqIqkIo2fOHHYdKNLeHIuDghRKIBGQ62x2uakkqdlfnJlLHgHuyHfhXqukUgbLWkd1dMASygfAg2iPQc0XXvh7a8IfIAlfvJdfFjUn4e6UWwueYWAO30bvdyWh3J6uK+U7k6+OevFXiVyfLMLQ8TLUSae+ilFkYgoeLUA+16AyeicB5aQWk9ewQ1FmOhBy9m6fJmMHLNeLwAji3wa7qMF8xT44EjksiVyqfmKT32f9VqMeSSBVLwp9D86xl3Y4iJPPc24tSmUZxIhAj/UvP7oHrYHZG7sMXekWVzl1MdCULegXvDV54e6tRjImXHpIYI="
        - secure: "ge4YG5C8X4c8igWyWLBLGvUYtdQqG1XcVU4biWSoGi3L0tKmxdPYLYZA82gVRe+UDKcKsiuwrH9BP8R/aw1qMzTA4xMQqlk5LFiwfLTmQ8QRYJzTA8TcpkT3S1cPBxjcOYPNia4GUfMtvsPeVepPwVi4MPXRbHyF2QlxH9mNg1hUr+qWQ3aZPw6k7jYtUPr9cs7DG7CKKqk7Pg9Cp4ZW7PZYEA7fiwBmqMT5J+MvwQxnxunAFfPhsQlxBBJu1Vc+dpXAvx6T7K6x87vcqr51gldGHTYWzRywZJ/Opo69Zl9Jv+d6pMe3CIFHkfMneECKgfaAH+w3wDwLQ0wKNTpk7FpPEXmSKo1xuATGh5/vqkiJrkTC7VgCaP5D2J12QflIfOPLafA7ikJfWEzgoccBn+d3jFkHEakdqh+Fh1s0ftLSTdpLtSzu56vBOV4kRE0+g8dv+8mEaQ5JqWQpyOMNHMtSS0a/PWJ1OGuFKWqMFuRPh0O0es0PXzRe2Y1FG/cdKuz+hU54od7lvqZqQPEaF1i8UaJ+T7YdRQRpm94HsEvBap48PL3ULrjq6rYd/q3Jf+vH7+UCHxengxt0UDiNDGfS/4vSvzbOFrYDcOXGV166FfG6Ldg9+CLtQHhhhzEmnZi19P6gQUlxdLnk/FYASYIDcz0+kgOAmzrVPlXw924="
        - secure: "VC+MLFtGnc25N0clZVCZ3/v6Qgt9sizkd4+JVoqTjdH+hccc3AiRRCB6U9btzkI6Xbd4ZincndwOSthWn5J7pn+sn6kdUWoNQWzVRm5hwkHp8tLmCZg8fhPsSpQ1cLfAKoZHJdWklv18jfqeQt+W8a36slq6sioj3t7C/hW8UyetSWhaJ6KL52U+j5Ry3meJzVjlblpLD0WNrP1C2dFHd9ut9gP9H+m3aZt7gzDqsLykVoGMCe7kxlp6vyeZHV1vzr/pSiUTy7UZUDfeSdFM4DS9llAzJ3WuQd8b1VHXmaB1t7NpXLcCW/nw+W1+RNeJzcumXYtIEDDisqDyBRw/Pb6HfQrkTv/OYjMxAZGmGRH19CeQElH88bqD57+mq7IcvTleAkj6GLiymeEUSAqIz/TtDzB1uQ0lGSj192svrsYy4R9icjlkXcYUNTnbqnqM148Rz5c3nYCLYiN7jIsfIE9G1A84Nbjy7jMEvMrBRLLsvWhnJKLnlyvqJcusXl1jCeotutP07vTOf9nfgaLBWrDQ5o/O/LU9cgZompSENdTOwtuVpC68R9Yqfmc/nIMqp/+i7gVoFUaiI/kj7MIvD9xladsiWSioJUnOGxK3Y7NaI0pIuS8VKT2XYDR9Lb60URz36TM7UpwadFFGL+vKYvUxBsDM3sftDvSZHOHuTdA="
      deploy:
        provider: releases
        api_key:
          secure: nU9hIbibh3INaCIHowyu+ePaBguumhtp+uv57T5sbS/e8lMFtu3uK0SAWF3PtBQ616TzJb7icYo6sUnlDYj/ihYUFk9WoS5IQ2hTOFFgN3X6LCjw2P+DS6dc9+sVS6EIDFpt+uqhaMmR+cHuUjfC032PolSZ6WXioKnDzYgPT4JTUDxrn3KEJH6w3xVP5MVVfpT+zfxpNgxfm3iNYxGYZ5ep0avbPcMUIcP12gs3ZLybfapgAFHyy0mAh0rKu908sjmUCShCYyzoM/f2J8YiPhVoHiABhh6dCDKw5RUR8ajZ6MXP1Iuxat2I7SyeKGlZnySrLKbi3vSgPfK1lRi4JVnGapm4rPUH+f/x0Vz6RP83N+wFXigZ28qSkqBtAcD0iEYCix9LPvK22iNeC34HNHKOE0Jon5cPJj4ZtqwCSvauV0JkfNaTbdQ/VummSgQLlc+zUf4+uY8jCZ1FDou6Et7G4AZEtKULHs9Jij58DZptC4ts8V5Hxr0/vz3zHROznGOcCuZ7k+cy7edTwkuL8yZNEjkWNBbguzyXYmY8eL+pzlVbRPQsCFmYe/Es+3mhKQrXn1gBCq3k8boOCRPH5sslBTvrGslgpvDZpmytE8LIGDLDytT/Pzr+H10K0EnM/uwIj1Oa9ejzASZL6JaUBZg/3jhnUOGlD2o8psEWD4A=
        file:
          - build/jtidy/jtidy/target/jtidy-${PV}.jar
          - build/jtidy/jtidy/target/jtidy-${PV}-sources.jar
          - build/jtidy/jtidy/target/jtidy-${PV}-test-sources.jar
        on:
          repo: jtidy/jtidy
          branch: master
          tags: true
        skip_cleanup: true
      script:
        - openssl aes-256-cbc -K $encrypted_c6bc1d197429_key -iv $encrypted_c6bc1d197429_iv -in private-key.gpg.enc -out private-key.gpg -d
        - gpg --import private-key.gpg
        - mvn versions:set -DnewVersion=${TRAVIS_TAG}
        - mvn clean deploy --settings settings.xml -DskipTests=true -B -U -Prelease
    - stage: SonarQube Scan
      if: tag IS blank
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
